#ChipScope Core Inserter Project File Version 3.0
#Thu Jun 01 10:52:49 CST 2017
Project.device.designInputFile=E\:\\ISE_Project\\PXI\\DSO_K7_ffg900_v2\\DSO_K7_ffg900\\PXI_DAQ_cs.ngc
Project.device.designOutputFile=E\:\\ISE_Project\\PXI\\DSO_K7_ffg900_v2\\DSO_K7_ffg900\\PXI_DAQ_cs.ngc
Project.device.deviceFamily=20
Project.device.enableRPMs=true
Project.device.outputDirectory=E\:\\ISE_Project\\PXI\\DSO_K7_ffg900_v2\\DSO_K7_ffg900\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=4
Project.filter<0>=
Project.filter<1>=clk*
Project.filter<2>=clk_*
Project.filter<3>=cl*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=ADC_Ctrlword_Send_Inst adc_set_clk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=ADC_Ctrlword_Send_Inst clk500K
Project.unit<0>.dataChannel<10>=ADC_Ctrlword_Send_Inst adc_con<26>
Project.unit<0>.dataChannel<11>=ADC_Ctrlword_Send_Inst adc_con<25>
Project.unit<0>.dataChannel<12>=ADC_Ctrlword_Send_Inst adc_con<24>
Project.unit<0>.dataChannel<13>=ADC_Ctrlword_Send_Inst adc_con<23>
Project.unit<0>.dataChannel<14>=ADC_Ctrlword_Send_Inst adc_con<22>
Project.unit<0>.dataChannel<15>=ADC_Ctrlword_Send_Inst adc_con<21>
Project.unit<0>.dataChannel<16>=ADC_Ctrlword_Send_Inst adc_con<20>
Project.unit<0>.dataChannel<17>=ADC_Ctrlword_Send_Inst adc_con<19>
Project.unit<0>.dataChannel<18>=ADC_Ctrlword_Send_Inst adc_con<18>
Project.unit<0>.dataChannel<19>=ADC_Ctrlword_Send_Inst adc_con<17>
Project.unit<0>.dataChannel<1>=ADC_Ctrlword_Send_Inst ADC_MOSI
Project.unit<0>.dataChannel<20>=ADC_Ctrlword_Send_Inst adc_con<16>
Project.unit<0>.dataChannel<21>=ADC_Ctrlword_Send_Inst adc_con<15>
Project.unit<0>.dataChannel<22>=ADC_Ctrlword_Send_Inst adc_con<14>
Project.unit<0>.dataChannel<23>=ADC_Ctrlword_Send_Inst adc_con<13>
Project.unit<0>.dataChannel<24>=ADC_Ctrlword_Send_Inst adc_con<12>
Project.unit<0>.dataChannel<25>=ADC_Ctrlword_Send_Inst adc_con<11>
Project.unit<0>.dataChannel<26>=ADC_Ctrlword_Send_Inst adc_con<10>
Project.unit<0>.dataChannel<27>=ADC_Ctrlword_Send_Inst adc_con<9>
Project.unit<0>.dataChannel<28>=ADC_Ctrlword_Send_Inst adc_con<8>
Project.unit<0>.dataChannel<29>=ADC_Ctrlword_Send_Inst adc_con<7>
Project.unit<0>.dataChannel<2>=ADC_Ctrlword_Send_Inst ADC_CSN
Project.unit<0>.dataChannel<30>=ADC_Ctrlword_Send_Inst adc_con<6>
Project.unit<0>.dataChannel<31>=ADC_Ctrlword_Send_Inst adc_con<5>
Project.unit<0>.dataChannel<32>=ADC_Ctrlword_Send_Inst adc_con<4>
Project.unit<0>.dataChannel<33>=ADC_Ctrlword_Send_Inst adc_con<3>
Project.unit<0>.dataChannel<34>=ADC_Ctrlword_Send_Inst adc_con<2>
Project.unit<0>.dataChannel<35>=ADC_Ctrlword_Send_Inst adc_con<1>
Project.unit<0>.dataChannel<36>=ADC_Ctrlword_Send_Inst adc_con<0>
Project.unit<0>.dataChannel<3>=ADC_Ctrlword_Send_Inst ADC_SCLK
Project.unit<0>.dataChannel<4>=ADC_Ctrlword_Send_Inst ADC_RSTN
Project.unit<0>.dataChannel<5>=ADC_Ctrlword_Send_Inst adc_con<31>
Project.unit<0>.dataChannel<6>=ADC_Ctrlword_Send_Inst adc_con<30>
Project.unit<0>.dataChannel<7>=ADC_Ctrlword_Send_Inst adc_con<29>
Project.unit<0>.dataChannel<8>=ADC_Ctrlword_Send_Inst adc_con<28>
Project.unit<0>.dataChannel<9>=ADC_Ctrlword_Send_Inst adc_con<27>
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=37
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=ADC_Ctrlword_Send_Inst clk500K
Project.unit<0>.triggerChannel<0><10>=ADC_Ctrlword_Send_Inst adc_con<26>
Project.unit<0>.triggerChannel<0><11>=ADC_Ctrlword_Send_Inst adc_con<25>
Project.unit<0>.triggerChannel<0><12>=ADC_Ctrlword_Send_Inst adc_con<24>
Project.unit<0>.triggerChannel<0><13>=ADC_Ctrlword_Send_Inst adc_con<23>
Project.unit<0>.triggerChannel<0><14>=ADC_Ctrlword_Send_Inst adc_con<22>
Project.unit<0>.triggerChannel<0><15>=ADC_Ctrlword_Send_Inst adc_con<21>
Project.unit<0>.triggerChannel<0><16>=ADC_Ctrlword_Send_Inst adc_con<20>
Project.unit<0>.triggerChannel<0><17>=ADC_Ctrlword_Send_Inst adc_con<19>
Project.unit<0>.triggerChannel<0><18>=ADC_Ctrlword_Send_Inst adc_con<18>
Project.unit<0>.triggerChannel<0><19>=ADC_Ctrlword_Send_Inst adc_con<17>
Project.unit<0>.triggerChannel<0><1>=ADC_Ctrlword_Send_Inst ADC_MOSI
Project.unit<0>.triggerChannel<0><20>=ADC_Ctrlword_Send_Inst adc_con<16>
Project.unit<0>.triggerChannel<0><21>=ADC_Ctrlword_Send_Inst adc_con<15>
Project.unit<0>.triggerChannel<0><22>=ADC_Ctrlword_Send_Inst adc_con<14>
Project.unit<0>.triggerChannel<0><23>=ADC_Ctrlword_Send_Inst adc_con<13>
Project.unit<0>.triggerChannel<0><24>=ADC_Ctrlword_Send_Inst adc_con<12>
Project.unit<0>.triggerChannel<0><25>=ADC_Ctrlword_Send_Inst adc_con<11>
Project.unit<0>.triggerChannel<0><26>=ADC_Ctrlword_Send_Inst adc_con<10>
Project.unit<0>.triggerChannel<0><27>=ADC_Ctrlword_Send_Inst adc_con<9>
Project.unit<0>.triggerChannel<0><28>=ADC_Ctrlword_Send_Inst adc_con<8>
Project.unit<0>.triggerChannel<0><29>=ADC_Ctrlword_Send_Inst adc_con<7>
Project.unit<0>.triggerChannel<0><2>=ADC_Ctrlword_Send_Inst ADC_CSN
Project.unit<0>.triggerChannel<0><30>=ADC_Ctrlword_Send_Inst adc_con<6>
Project.unit<0>.triggerChannel<0><31>=ADC_Ctrlword_Send_Inst adc_con<5>
Project.unit<0>.triggerChannel<0><32>=ADC_Ctrlword_Send_Inst adc_con<4>
Project.unit<0>.triggerChannel<0><33>=ADC_Ctrlword_Send_Inst adc_con<3>
Project.unit<0>.triggerChannel<0><34>=ADC_Ctrlword_Send_Inst adc_con<2>
Project.unit<0>.triggerChannel<0><35>=ADC_Ctrlword_Send_Inst adc_con<1>
Project.unit<0>.triggerChannel<0><36>=ADC_Ctrlword_Send_Inst adc_con<0>
Project.unit<0>.triggerChannel<0><3>=ADC_Ctrlword_Send_Inst ADC_SCLK
Project.unit<0>.triggerChannel<0><4>=ADC_Ctrlword_Send_Inst ADC_RSTN
Project.unit<0>.triggerChannel<0><5>=ADC_Ctrlword_Send_Inst adc_con<31>
Project.unit<0>.triggerChannel<0><6>=ADC_Ctrlword_Send_Inst adc_con<30>
Project.unit<0>.triggerChannel<0><7>=ADC_Ctrlword_Send_Inst adc_con<29>
Project.unit<0>.triggerChannel<0><8>=ADC_Ctrlword_Send_Inst adc_con<28>
Project.unit<0>.triggerChannel<0><9>=ADC_Ctrlword_Send_Inst adc_con<27>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=37
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
