#ChipScope Core Inserter Project File Version 3.0
#Fri May 26 10:49:05 CST 2017
Project.device.designInputFile=E\:\\ISE_Project\\PXI\\DSO_K7_ffg900_v2\\DSO_K7_ffg900\\PXI_DAQ_cs.ngc
Project.device.designOutputFile=E\:\\ISE_Project\\PXI\\DSO_K7_ffg900_v2\\DSO_K7_ffg900\\PXI_DAQ_cs.ngc
Project.device.deviceFamily=20
Project.device.enableRPMs=true
Project.device.outputDirectory=E\:\\ISE_Project\\PXI\\DSO_K7_ffg900_v2\\DSO_K7_ffg900\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=15
Project.filter<0>=data_rx_NEW_out*
Project.filter<10>=Signal_Data
Project.filter<11>=rx_CH_DCBA_fix_out
Project.filter<12>=data_from_ADC
Project.filter<13>=data_from_ADC*
Project.filter<14>=adc_clk_out1
Project.filter<1>=data_rx_NEW_out
Project.filter<2>=
Project.filter<3>=dout_fifo_adc*
Project.filter<4>=Signal_Trig_test
Project.filter<5>=d_rfifo*
Project.filter<6>=RD_DDR_TEST_DATA*
Project.filter<7>=RD_DDR_TEST_DATA
Project.filter<8>=rx_CH_DCBA_fix_out*
Project.filter<9>=Signal_Data*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=adc_clk_out1
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=ADC_DATA_RX_Inst Signal_Data<7>
Project.unit<0>.dataChannel<10>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<5>
Project.unit<0>.dataChannel<11>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<4>
Project.unit<0>.dataChannel<12>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<3>
Project.unit<0>.dataChannel<13>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<2>
Project.unit<0>.dataChannel<14>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<1>
Project.unit<0>.dataChannel<15>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<0>
Project.unit<0>.dataChannel<16>=_i000008 dout_fifo_adc<7>
Project.unit<0>.dataChannel<17>=_i000008 dout_fifo_adc<6>
Project.unit<0>.dataChannel<18>=_i000008 dout_fifo_adc<5>
Project.unit<0>.dataChannel<19>=_i000008 dout_fifo_adc<4>
Project.unit<0>.dataChannel<1>=ADC_DATA_RX_Inst Signal_Data<6>
Project.unit<0>.dataChannel<20>=_i000008 dout_fifo_adc<3>
Project.unit<0>.dataChannel<21>=_i000008 dout_fifo_adc<2>
Project.unit<0>.dataChannel<22>=_i000008 dout_fifo_adc<1>
Project.unit<0>.dataChannel<23>=_i000008 dout_fifo_adc<0>
Project.unit<0>.dataChannel<24>=Signal_Trig_test
Project.unit<0>.dataChannel<2>=ADC_DATA_RX_Inst Signal_Data<5>
Project.unit<0>.dataChannel<3>=ADC_DATA_RX_Inst Signal_Data<4>
Project.unit<0>.dataChannel<4>=ADC_DATA_RX_Inst Signal_Data<3>
Project.unit<0>.dataChannel<5>=ADC_DATA_RX_Inst Signal_Data<2>
Project.unit<0>.dataChannel<6>=ADC_DATA_RX_Inst Signal_Data<1>
Project.unit<0>.dataChannel<7>=ADC_DATA_RX_Inst Signal_Data<0>
Project.unit<0>.dataChannel<8>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<7>
Project.unit<0>.dataChannel<9>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<6>
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=25
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=ADC_DATA_RX_Inst Signal_Data<7>
Project.unit<0>.triggerChannel<0><10>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<5>
Project.unit<0>.triggerChannel<0><11>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<4>
Project.unit<0>.triggerChannel<0><12>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<3>
Project.unit<0>.triggerChannel<0><13>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<2>
Project.unit<0>.triggerChannel<0><14>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<1>
Project.unit<0>.triggerChannel<0><15>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<0>
Project.unit<0>.triggerChannel<0><16>=_i000008 dout_fifo_adc<7>
Project.unit<0>.triggerChannel<0><17>=_i000008 dout_fifo_adc<6>
Project.unit<0>.triggerChannel<0><18>=_i000008 dout_fifo_adc<5>
Project.unit<0>.triggerChannel<0><19>=_i000008 dout_fifo_adc<4>
Project.unit<0>.triggerChannel<0><1>=ADC_DATA_RX_Inst Signal_Data<6>
Project.unit<0>.triggerChannel<0><20>=_i000008 dout_fifo_adc<3>
Project.unit<0>.triggerChannel<0><21>=_i000008 dout_fifo_adc<2>
Project.unit<0>.triggerChannel<0><22>=_i000008 dout_fifo_adc<1>
Project.unit<0>.triggerChannel<0><23>=_i000008 dout_fifo_adc<0>
Project.unit<0>.triggerChannel<0><24>=Signal_Trig_test
Project.unit<0>.triggerChannel<0><25>=ADC_DATA_RX_Inst data_rx_NEW_out<7>
Project.unit<0>.triggerChannel<0><26>=ADC_DATA_RX_Inst data_rx_NEW_out<6>
Project.unit<0>.triggerChannel<0><27>=ADC_DATA_RX_Inst data_rx_NEW_out<5>
Project.unit<0>.triggerChannel<0><28>=ADC_DATA_RX_Inst data_rx_NEW_out<4>
Project.unit<0>.triggerChannel<0><29>=ADC_DATA_RX_Inst data_rx_NEW_out<3>
Project.unit<0>.triggerChannel<0><2>=ADC_DATA_RX_Inst Signal_Data<5>
Project.unit<0>.triggerChannel<0><30>=ADC_DATA_RX_Inst data_rx_NEW_out<2>
Project.unit<0>.triggerChannel<0><31>=ADC_DATA_RX_Inst data_rx_NEW_out<1>
Project.unit<0>.triggerChannel<0><32>=ADC_DATA_RX_Inst data_rx_NEW_out<0>
Project.unit<0>.triggerChannel<0><3>=ADC_DATA_RX_Inst Signal_Data<4>
Project.unit<0>.triggerChannel<0><4>=ADC_DATA_RX_Inst Signal_Data<3>
Project.unit<0>.triggerChannel<0><5>=ADC_DATA_RX_Inst Signal_Data<2>
Project.unit<0>.triggerChannel<0><6>=ADC_DATA_RX_Inst Signal_Data<1>
Project.unit<0>.triggerChannel<0><7>=ADC_DATA_RX_Inst Signal_Data<0>
Project.unit<0>.triggerChannel<0><8>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<7>
Project.unit<0>.triggerChannel<0><9>=ADC_DATA_RX_Inst rx_CH_DCBA_fix_out<6>
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=33
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
